name: Publish docs.openeo.cloud
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Daily run to refresh external resources
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: npm install
      - run: npm run build
      - run: cp CNAME .vuepress/dist/CNAME
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vuepress/dist
          user_name: 'openEO CI'
          user_email: openeo.ci@uni-muenster.de