name: Publish docs.openeo.cloud
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Daily run to refresh external resources
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16' # https://github.com/vuejs/vue-cli/issues/6770
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: npm install
      - run: npm run build
      - run: cp CNAME .vuepress/dist/CNAME
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vuepress/dist
          user_name: 'openEO CI'
          user_email: openeo.ci@uni-muenster.de
